# -*- coding: utf-8 -*-
"""Sistem panen (TTS 4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Viel8IyFkGIZYujKRWMm2-IQJw4cvDDv
"""

# main.py
# Program Pencatatan Hasil Panen Digital
# Versi awal: mencatat data hasil panen dan menghitung totalnya

data_panen = {
    "Padi": 120,
    "Jagung": 80,
    "Kedelai": 45
}

def hitung_total(data):
    """Menghitung total hasil panen (dalam kg) dari seluruh komoditas."""
    return sum(data.values())

def main():
    total = hitung_total(data_panen)
    print("=== Laporan Hasil Panen ===")
    for komoditas, jumlah in data_panen.items():
        print(f"{komoditas}: {jumlah} kg")
    print(f"Total hasil panen: {total} kg")

if __name__ == "__main__":
    main()